version: 'v2.29.7'
services:
    client:
        stdin_open: true
        container_name: client
        build:
            context: .
            dockerfile: Dockerfile.dev # Use Dockerfile.dev for development
        ports:
            - '5173:5173' # Map container port to the host port
        volumes:
            - /app/node_modules # Exclude node_modules from being mounted
            - ./:/app # Mount the project directory for live changes
