# Use Node.js 22 Alpine image
FROM node:22-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json /app
RUN yarn install --silent

# Copy all files from the current directory into the container
COPY . /app

# Expose the development port
EXPOSE 5173

# Start the app in development mode
CMD ["yarn", "start"]
